export default [
    {
        _id: 1,
        userName: 'Elon Musk',
        handle: 'elonmusk',
        time: '23h',
        remark: 'Amazing show about this misson!',
        displayPicture: 'https://pbs.twimg.com/profile_images/1442634650703237120/mXIcYtIs_400x400.jpg',
        title: 'Countdown: Inspiration rocket to fire off soon',
        image: 'https://giantavocado.games/wp-content/uploads/2021/01/spaceman-avocado.jpg',
        content: 'lorem ipusm dolor si amet lorem ipusm dolor si amet lorem ipusm dolor si amet lorem ipusm dolor si amet lorem ipusm dolor si amet lorem ipusm dolor si amet lorem ipusm dolor si amet lorem ipusm dolor si amet',
        comments: '4.2K',
        retweets: '4.2K',
        likes: '4.2K',
        link: 'netflix.com',
    },
    {
        _id: 2,
        userName: 'New York Post',
        handle: 'nypost',
        time: '23h',
        remark: 'Grimes seen reading Karl Marx',
        displayPicture: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTKog0n6F-KH0hD037U05f2yZos3LRWg8X30A&usqp=CAU',
        title: 'Grimes is reading karl marx again',
        image: 'https://pbs.twimg.com/media/FAuW2GlXIAIOBN7.jpg',
        content: 'Click here to know more lorem ipsum lorem ipsum lorem ipsum',
        comments: '965',
        retweets: '2.4K',
        likes: '4K',
        link: 'nypost.com',
    },
];
